### ISSUE TITLE
Add milabench install step to README?

### ISSUE THREAD

**Issue by aurotripathy** [mila-iqia/training#19]
I think milabench is new and I got a `ModuleNotFoundError: No module named 'milabench'` until I installed it with.
`~/training/milabench# python setup.py install`

Am I doing this right?

**Comment by breuleux** [comment]
You can install it with `pip install -e milabench`. The `./install_python_dependencies.sh` step in the README should do it for you, among other things (it's the `-e milabench` entry in `requirements.txt`).

**Comment by aurotripathy** [comment]
Thank you. 
I skipped  steps. 
I'll review the README carefully. 
Closing.
